// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD41MRWi_qq0W2LGahovfd83fw6NUxNe1I',
    appId: '1:35518635173:web:1bc047e97ab4164a69c14c',
    messagingSenderId: '35518635173',
    projectId: 'farmingauth-8ae5a',
    authDomain: 'farmingauth-8ae5a.firebaseapp.com',
    storageBucket: 'farmingauth-8ae5a.firebasestorage.app',
    measurementId: 'G-KHBQTXNGY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg6watGIyLBKbys2a5JH_yOK84JeCZAlQ',
    appId: '1:35518635173:android:07301b40bfbc7f0a69c14c',
    messagingSenderId: '35518635173',
    projectId: 'farmingauth-8ae5a',
    storageBucket: 'farmingauth-8ae5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRbjwuHhDVmZvUJUi542rQBlGySdDQKKk',
    appId: '1:35518635173:ios:35d2fae6e30aaf3469c14c',
    messagingSenderId: '35518635173',
    projectId: 'farmingauth-8ae5a',
    storageBucket: 'farmingauth-8ae5a.firebasestorage.app',
    iosBundleId: 'com.org.catalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRbjwuHhDVmZvUJUi542rQBlGySdDQKKk',
    appId: '1:35518635173:ios:35d2fae6e30aaf3469c14c',
    messagingSenderId: '35518635173',
    projectId: 'farmingauth-8ae5a',
    storageBucket: 'farmingauth-8ae5a.firebasestorage.app',
    iosBundleId: 'com.org.catalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD41MRWi_qq0W2LGahovfd83fw6NUxNe1I',
    appId: '1:35518635173:web:940d00988510910469c14c',
    messagingSenderId: '35518635173',
    projectId: 'farmingauth-8ae5a',
    authDomain: 'farmingauth-8ae5a.firebaseapp.com',
    storageBucket: 'farmingauth-8ae5a.firebasestorage.app',
    measurementId: 'G-LL8SBZVRCH',
  );
}
